config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :parties

  resources :restaurants

  get 'users/new'

  root              'static_pages#search'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'search'  =>  'static_pages#search'
  get 'check_status'  =>  'static_pages#check_status'
  
  get 'search_results'  =>  'static_pages#search'
  get 'staff_home'  =>  'static_pages#staff_home'
  get 'signup'  =>  'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :parties
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'cancel_party' => 'parties#cancel_party'
  get 'drop_party' => 'parties#drop_party'
  get 'parties/:id/table_ready' => 'parties#table_ready'
  get 'parties/:id/notify' => 'parties#notify'
  get 'twilio/send_sms' => 'twilio#send_sms'
  get 'twilio/receive_sms' => 'twilio#receive_sms'

  get  'restaurants/:id/estwait' => 'restaurants#estwait'

  post 'api/signup'
  post 'api/signin'
  post 'api/reset_password'

  get 'api/get_waitlist'
  post 'api/add_party'
  get 'api/get_restaurant'
  delete 'api/seat_party'  => 'parties#seat_party'
    
  get 'api/get_token'  
  get 'api/clear_token'

end

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "#{$site_name}", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Restaurants", restaurants_path %></li>
            <li><%= link_to "Parties", parties_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.first_name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Restaurants", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Check Status", check_status_path %></li>
          <li><%= link_to "Log in/Sign Up", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>